### ISSUE TITLE
Curse Download-Links wurden geändert, keine aktualisierung mehr möglich

### ISSUE THREAD

**Issue by LuxWare** [ArndtB/WoW-Addon-Updater#5]
Hallo,

Curse scheint den Aufbau seiner Downloadlinks geändert zu haben.
Dadurch kann kein Download-Link mehr von deinem Programm gefunden werden, wodurch es letztendlich zu einem Fehler kommt.
![grafik](https://user-images.githubusercontent.com/28117556/32667154-2e406880-c63a-11e7-941d-5f5fc40dd88c.png)
Ich habe hier mal einen Ausschnitt aus dem Log, mit nur einem Addon.
Zu beachten ist, dass ich hier bereits versucht habe mit der neuen domain von curse zu arbeiten.
Man erkennt auch schon am Addon-Namen, dass die Antwort auf deinen http-request geändert worden sein muss.

[Bug.log](https://github.com/ArndtB/WoW-Addon-Updater/files/1461962/Bug.log)

Der Alte Link war: https://mods.curse.com/addons/wow/atlas
Dieser wird noch sauber zum neuen weitergeleitet, weshalb es prinzipiell sogar möglich sein sollte, in der Addon-DB die alte "Addon-URL" bei zu behalten und nur den Code für die Download-URL anzupassen.

Auf lange sich wäre es aber wohl ratsam, auch die Addon-URL zu aktualisieren, sofern man feststellen kann, dass man weitergeleitet wurde. (Notfalls muss dies eben der Nutzer selbst einmal für alle Addons durchführen)

Viele Grüße

**Comment by ArndtB** [comment]
Hallo & vielen Dank für die Rückinfo. Das bedeutet etwas Arbeit, ich werde mir das im Laufe der nächsten Woche genauer anschauen.

**Comment by Aur0r4** [comment]
Ich wollte das ganze gerade eben auch gemeldet haben, aber da war wohl wer schneller. Vielen Dank das du dich darum kümmern möchtest. Ich habe deinen WoW-Addon-Updater in den letzten Monaten echt zu schätzen gelernt.

**Comment by ArndtB** [comment]
Hallo nochmal und danke für Eure Geduld. Der Aufbau der Webseiten hat sich leider grundlegend geändert, hierzu musste ich die Kernroutinen überarbeiten, um die Inhalte entsprechend parsen zu können. Parallel habe ich eine Routine implementiert, welche die Addon-Datenbank auf den benötigten neuen Stand bringt, ohne dass der Addon-Bestand neu eingerichtet werden muss. Ich hoffe, das nun alles wie gewünscht funktioniert. Die Sourcen habe ich gerade frisch hochgeladen, die Binarys folgen dann morgen Abend. Viele Grüße & eine gute Nacht an meine Nutzergemeinde :-)

**Comment by LuxWare** [comment]
Hey, vielen Dank für die Mühe und die Überstunden :-D. Freue mich schon darauf die neue Version zu Nutzen.

**Comment by ArndtB** [comment]
Hallo zusammen, 
wie versprochen, habe ich die Binaries hochgeladen und wünsche Euch viel Freude mit der neuen Version und freue mich auf Euer Feedback :-)

**FIXED with 2.2.0 - release**

**Comment by Aur0r4** [comment]
Hallo Arndt, vielen Dank das es so schnell ging, ein erster Test war erfolgreich! :)
