### ISSUE TITLE
Curseforge | Status : Error

### ISSUE THREAD

**Issue by Smallinger** [ArndtB/WoW-Addon-Updater#6]
Hallo, ich habe seit dem Update von Curse, ein Problem mit dem WoW-Addon-Updater.
Ich habe sogar schon mein PC neu gemacht, und das Programm frisch gestartet, immer wenn ich versuche nun ein Addon Hinzuzufügen gibt er direkt ein Error raus.

hier mal ein Screenshot
![3jevqs](https://user-images.githubusercontent.com/8080568/33019446-ac7f6c56-cdfa-11e7-84b2-1ce6fc64e55d.png)

hier findest du die [log.txt](https://github.com/ArndtB/WoW-Addon-Updater/files/1487684/log.txt)

**Comment by ArndtB** [comment]
Hallo, bitte entschuldige die späte Antwort, ich bin erst heute dazu gekommen. Ich kann das Problem leider nicht reproduzieren, unter Windows, Linux und macOS ist die Funktion gegeben und es treten keinerlei Fehler auf. Bitte teste noch einmal erneut - es ist durchaus möglich, das es an diesem Tag Probleme mit der Website selbst oder dem betreffenden Addon gab.

**Comment by Smallinger** [comment]
Hallo, danke für deine Antwort leider hat es nichts gebracht, ich habe dir auch nochmal ein Video gemacht.
https://streamable.com/ydly0

Ich habe vorher auch alle Einstellungen gelöscht die in AppData/local gespeichert werden, damit das Programm wirklich auf null ist.

**Comment by ArndtB** [comment]
Hallo nochmal & danke für Deine Mühe mit dem Video. Ich habe zwischenzeitlich eine frische Windows 7 - Installation auf einer VM aktiviert und es hier nochmal getestet - diesmal liess sich das Problem reproduzieren. 

Durch die Umstellung der Websites ist nun OpenSSL auch auf den Windows-Installationen erforderlich (siehe beigefügter Screenshot) - bis auf Windows 10, hier gibt es offenbar keine Probleme. 

OpenSSL kannst Du z.B. hier finden: https://wiki.openssl.org/index.php/Binaries . Die DLL-Files müssen sich in einem Suchpfad oder im Verzeichnis des Addon-Updaters befinden - dann sollte alles wie gewünscht funktionieren; bitte gib mir dann kurz Bescheid. Für die Zukunft schaue ich, ob sich noch eine andere Möglichkeit finden lässt.

Ich wünsche noch einen schönen Sonntag :-)

![bildschirmfoto 2017-11-26 um 17 21 04](https://user-images.githubusercontent.com/17092004/33242094-a236c3dc-d2cf-11e7-8b70-d503a4ce0847.png)

**Comment by Smallinger** [comment]
Hallo, ArndtB

Mein Betriebssystem ist Windows 10 Pro 64x, habe mir also "openssl-1.0.2m-x64_86-win64" besorgt und siehe da, es funktioniert wieder wie es soll 🥇
Vielen Dank!

Du hast gesagt das es bei Windows 10 keine Probleme gibt, doch genau auf diesen Operation System bin ich frisch installiert, mit der neusten ISO vom Microsoft MedianCreationTool + alle Updates heruntergeladen.

**Comment by gCurse** [comment]
Ich habe das gleiche Problem unter Linux. Curseforge funktioniert nicht.
Updaten von ElvUI funktioniert allerdings. Eine Idee?

[wau.log](https://github.com/ArndtB/WoW-Addon-Updater/files/1546912/wau.log)

**Comment by ArndtB** [comment]
Ich habe noch ein paar Tests durchgeführt, durch die Umstellung der Websites ist nun auf allen Systemen OpenSSL erforderlich, wie ich schon vermutet habe.

Für Linux hatte ich dies auch in den Release-Notes vermerkt:
> IMPORTANT FOR LINUX SYSTEMS: Package libssl-dev is strongly required for functionality! Please install it, for example on Debian based Systems, as follows: apt install libssl-dev

@gCurse : Ich weiß leider nicht, welche Distribution Du verwendest, doch prüfe bitte einmal, ob das Paket `libssl-dev` installiert ist. Falls nicht, installiere dieses bitte nach - dann sollte alles wieder zufriedenstellend funktionieren.

Für die Zukunft schaue ich wie gesagt, ob sich noch eine andere Möglichkeit finden lässt, ich versuche es nach den Feiertagen.

**Comment by ArndtB** [comment]
Release-Notes updated:
>*Added on December, 11th 2017:*
**IMPORTANT FOR WINDOWS SYSTEMS:** OpenSSL is strongly required for functionality! Please install required DLL-Files in search path or directly in WoW-Addon-Updater-Directory. You can find OpenSSL here, for example: https://wiki.openssl.org/index.php/Binaries

**Comment by gCurse** [comment]
Ich benutze [Artixlinux](https://artixlinux.org) (Archlinux basiert).
Openssl v1.1.0 (als Standard) und openssl-1.0 v1.0.2 sind installiert.
Vielleicht liegt es an der neueren openssl Version.

**Comment by ArndtB** [comment]
@gCurse: Bitte versuche ergänzend auch die Installation der 32-Bit OpenSSL Library (multilib Repository). 

Viele Grüße 

Arndt

**Comment by gCurse** [comment]
lib32-openssl v1.1.0 war schon installiert. Ich habe jetzt dazu noch lib32-openssl-1.0 v1.0.2 installiert und .config/WoW-Addon-Updater gelöscht. Gleicher Fehler wie bisher.
Wenn es an openssl liegt, sollte dann nicht auch bei ElvUI ein Fehler auftreten? Hmm..

[wau.log](https://github.com/ArndtB/WoW-Addon-Updater/files/1555878/wau.log)

**Comment by ArndtB** [comment]
Hallo Dirk, 

vielen Dank für die detaillierten Angaben, jetzt lässt es sich besser eingrenzen. Der Fehler tritt bei der Ermittlung der Download-URL auf, denn auch hier mußte ich die Routine aufgrund der Website-Umstellungen grundlegend überarbeiten. Bei ElvUi ist diese URL mehr oder weniger statisch, weshalb dieser Fehler dort nicht auftritt. 

Die aus der Methode resultierende Fehlermeldung `Exception class 'ESSL': Failed to create SSL Context` scheint hier der Schlüssel zu sein, ich habe hierzu folgendes im Lazarus-Forum gefunden: 
http://forum.lazarus.freepascal.org/index.php?topic=39206.0

Gerade der letzte Post scheint Deine erste Vermutung mit der neuen OpenSSL-Version zu bestätigen:

>After modification of the version string the same error is still raised. I suspect an API breakage from 1.0.X to 1.1.X. Can anyone run the sample above with SSL 1.1 (1.1.0f or 1.1.0g) ?

Du könntest höchstens probieren, (testweise) für den Übergang eine ältere Version zu verwenden, bis sich eine andere Lösung finden lässt. 

Ich wünsche Dir (und natürlich allen Mitlesenden auch :-) ) ein schönes Weihnachtsfest und alles Gute für das neue Jahr.

Viele Grüße

Arndt

**Comment by gCurse** [comment]
So funktioniert es jetzt bei mir:

`mkdir -p ${HOME}/.local/opt/wau/lib`
`ln -s /usr/lib/libcrypto.so.1.0.0 ${HOME}/.local/opt/wau/lib/libcrypto.so`
`ln -s /usr/lib/libssl.so.1.0.0 ${HOME}/.local/opt/wau/lib/libssl.so`

WoW-Addon-Updater_2.2.0_Linux_x64.zip nach `${HOME}/.local/opt/wau` entpacken
Folgendes Shellscript in `${HOME}/.local/opt/wau` erstellen und ausführbar machen:

`#/usr/bin/env sh`
`LD_LIBRARY_PATH=${HOME}/.local/opt/wau/lib`
`export LD_LIBRARY_PATH`
`exec ${HOME}/.local/opt/wau/addonupd "$@"`

**Comment by ArndtB** [comment]
Hallo zusammen & ein frohes neues Jahr :-) 
Vorweg ein kurzer Status; ich habe möglicherweise eine Lösung, welche die zusätzliche Installation der OpenSSL-Bibliotheken überflüssig macht. Ich werde diese testen und bei Erfolg mit dem nächsten Release implementieren.

**Comment by ArndtB** [comment]
Hallo nochmal :-) Ich habe in den letzten Wochen viele Anpassungen vorgenommen und neue Features implementiert, nun ist es soweit: die neue Version 3.0 ist fertig! Diese sollte nun auch die OpenSSL-Problematik beheben, wie in meinem vorherigen Posting angekündigt. Ich wünsche viel Spaß mit der neuen Version: [https://github.com/ArndtB/WoW-Addon-Updater/releases/tag/3.0.0](https://github.com/ArndtB/WoW-Addon-Updater/releases/tag/3.0.0).
