### ISSUE TITLE
Feature Request: More than Curse

### ISSUE THREAD

**Issue by eTzmNcbkrng** [ArndtB/WoW-Addon-Updater#7]
Hi, I've just downloaded the app today and I'm liking what I see but I think it's missing a key feature in allowing downloading of AddOns from alternative sources.

Some AddOns on WoWinterface.com are not available on curse so I think this would be a good one to start with.

As an advanced function, there should also be the possibility to clone git repos into separate folder so that these can be symlinked to the AddOns folder, this would give us access to some of the AddOns on git.tukui.org and/or dev versions of AddOn on Github etc.

See config of my ElvUI addons for example;
![elvuisymlinks](https://user-images.githubusercontent.com/26512802/34549448-883718ee-f16d-11e7-9c16-636b362cf7bb.png)

Lastly, I think the application need to do an automatic replacement when the wrong Curse URL is entered, for example, this;
https://wow.curseforge.com/projects/master-plan
should be changed to this
https://www.curseforge.com/wow/addons/master-plan

**Comment by ArndtB** [comment]
Hello and thank you for the really good suggestions! I'll look at that, but I can not promise anything yet.

**Comment by ArndtB** [comment]
Hello again, I am pleased to announce the new release 3.0, with a lot of new features and improvements, including the integration of WoWInterface. Please take a look: [https://github.com/ArndtB/WoW-Addon-Updater/releases/tag/3.0.0](https://github.com/ArndtB/WoW-Addon-Updater/releases/tag/3.0.0).
